apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: versioning
  name: versioning
spec:
  replicas: 5
  selector:
    matchLabels:
      app: versioning
  strategy: {}
  template:
    metadata:
      labels:
        app: versioning
    spec:
      containers:
      - image: gitops/strategy:v2
        name: versioning
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
